version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # requirements.txt kök dizindeyse "/" kalsın
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "yt-dlp"